//
//  ShoppingListView.swift
//  Kitchen Companion
//
//  Created by Carmelo Stivala on 3/10/2026.
//

import SwiftUI

// What the household still needs to buy, and what they have already bought.
// Ticking an item off adds it to the pantry.
struct ShoppingListView: View {
    @ObservedObject var viewModel: KitchenViewModel
    @State private var isAddingItem = false

    private var pendingItems: [ShoppingListItem] {
        viewModel.shoppingItems.filter { $0.status == .pending }
    }

    private var purchasedItems: [ShoppingListItem] {
        viewModel.shoppingItems.filter { $0.status == .purchased }
    }

    var body: some View {
        NavigationStack {
            List {
                if viewModel.shoppingItems.isEmpty {
                    ContentUnavailableView(
                        "Nothing to buy",
                        systemImage: "cart",
                        description: Text("Add items yourself, or open a recipe and add what it is missing.")
                    )
                }

                if !pendingItems.isEmpty {
                    Section("To buy") {
                        ForEach(pendingItems) { item in
                            pendingRow(item)
                        }
                    }
                }

                if !purchasedItems.isEmpty {
                    Section("Bought") {
                        ForEach(purchasedItems) { item in
                            purchasedRow(item)
                        }
                    }
                }
            }
            .navigationTitle("Shopping List")
            .toolbar {
                ToolbarItem(placement: .topBarTrailing) {
                    Button {
                        isAddingItem = true
                    } label: {
                        Image(systemName: "plus.circle.fill").font(.title2)
                    }
                    .accessibilityLabel("Add Shopping Item")
                }
            }
            .sheet(isPresented: $isAddingItem) {
                AddShoppingItemView(viewModel: viewModel)
            }
            .alert("Shopping List", isPresented: Binding(
                get: { viewModel.noticeMessage != nil },
                set: { _ in viewModel.noticeMessage = nil }
            )) {
                Button("OK", role: .cancel) {}
            } message: {
                Text(viewModel.noticeMessage ?? "")
            }
        }
    }

    private func pendingRow(_ item: ShoppingListItem) -> some View {
        HStack {
            Button {
                viewModel.markPurchased(item)
            } label: {
                Image(systemName: "circle").font(.title3)
            }
            .buttonStyle(.plain)
            .accessibilityLabel("Mark \(item.ingredientName) as bought")

            VStack(alignment: .leading, spacing: 2) {
                Text(item.ingredientName).font(.headline)
                Text(originText(for: item))
                    .font(.caption)
                    .foregroundStyle(.secondary)
            }
            Spacer()
            Text(item.quantityNeeded.displayText)
                .foregroundStyle(.secondary)
        }
        .swipeActions {
            Button("Delete", role: .destructive) {
                viewModel.deleteShoppingItem(item)
            }
        }
    }

    private func purchasedRow(_ item: ShoppingListItem) -> some View {
        HStack {
            Image(systemName: "checkmark.circle.fill")
                .font(.title3)
                .foregroundStyle(.green)
            Text(item.ingredientName)
                .strikethrough()
            Spacer()
            Text(item.quantityNeeded.displayText)
        }
        .foregroundStyle(.secondary)
        .swipeActions {
            Button("Delete", role: .destructive) {
                viewModel.deleteShoppingItem(item)
            }
        }
    }

    private func originText(for item: ShoppingListItem) -> String {
        switch item.origin {
        case .manuallyAdded:
            return "Added by you"
        case .autoGenerated(let recipeID):
            let title = viewModel.recipes.first { $0.id == recipeID }?.title
            return title.map { "Needed for \($0)" } ?? "Needed for a recipe"
        }
    }
}

#Preview {
    ShoppingListView(viewModel: KitchenViewModel())
}
