//
//  GenerateShoppingListUseCase.swift
//  Kitchen Companion
//
//  Created by Carmelo Stivala on 1/10/2026.
//

import Foundation

// Turns one recipe ingredient shortfall into a shopping list item.
// Business rule: never create a second pending item for an ingredient
// that's already pending on the list, the household would end up buying
// it twice.
struct GenerateShoppingListUseCase {
    enum Failure: LocalizedError, Equatable {
        case duplicatePendingItem(ingredientName: String)
        case cannotDetermineQuantity(ingredientName: String)

        var errorDescription: String? {
            switch self {
            case .duplicatePendingItem(let ingredientName):
                return "\"\(ingredientName)\" is already on the shopping list. Check off the existing item instead of adding it twice."
            case .cannotDetermineQuantity(let ingredientName):
                return "\"\(ingredientName)\" is recorded in a different unit to what the recipe needs, so the amount to buy can't be worked out automatically. Add it to the list yourself."
            }
        }
    }

    func execute(
        shortfall: IngredientShortfall,
        recipeID: RecipeIdentifier,
        existingItems: [ShoppingListItem]
    ) -> Result<ShoppingListItem, Failure> {
        let ingredientName = shortfall.requirement.ingredientName
        let normalizedName = ingredientName.trimmingCharacters(in: .whitespacesAndNewlines).lowercased()

        let alreadyPending = existingItems.contains {
            $0.normalizedIngredientName == normalizedName && $0.status == .pending
        }
        guard !alreadyPending else {
            return .failure(.duplicatePendingItem(ingredientName: ingredientName))
        }

        let quantityNeeded: Quantity
        switch shortfall.reason {
        case .missingEntirely:
            quantityNeeded = shortfall.requirement.requiredQuantity
        case .insufficientQuantity(let haveQuantity):
            quantityNeeded = Quantity(
                amount: shortfall.requirement.requiredQuantity.amount - haveQuantity.amount,
                unit: shortfall.requirement.requiredQuantity.unit
            )
        case .unitMismatch:
            // Same honesty rule as Quantity.covers: don't guess a quantity
            // across units the household would need to convert themselves.
            return .failure(.cannotDetermineQuantity(ingredientName: ingredientName))
        }

        let item = ShoppingListItem(
            id: UUID().uuidString,
            ingredientName: ingredientName,
            quantityNeeded: quantityNeeded,
            origin: .autoGenerated(recipeID: recipeID),
            status: .pending
        )
        return .success(item)
    }
}
