//
//  ShoppingListItem.swift
//  Kitchen Companion
//
//  Created by Carmelo Stivala on 29/9/2026.
//

import Foundation

// Where a shopping list item came from.
// Represents whether the household typed this item in themselves, or the
// app generated it automatically because a recipe needed an ingredient
// they didn't have enough of.
enum ShoppingListItemOrigin: Equatable, Codable {
    case manuallyAdded
    case autoGenerated(recipeID: RecipeIdentifier)
}

// Whether a shopping list item still needs buying, or has been bought.
// Business rule: an item can only move from .pending to .purchased,
// enforced by MarkShoppingItemPurchasedUseCase, not by this type itself.
enum ShoppingListItemStatus: Equatable, Codable {
    case pending
    case purchased
}

// One entry on the household's shopping list.
// Represents something the household needs to buy, either typed in by
// hand, or generated because a recipe's ingredient requirement wasn't met
// by current pantry stock (see IngredientShortfall in RecipeFeasibility.swift).
// Business rule: GenerateShoppingListUseCase must never create a duplicate
// pending item for an ingredient that's already pending on the list.
struct ShoppingListItem: Identifiable, Equatable, Codable {
    let id: String
    var ingredientName: String
    var quantityNeeded: Quantity
    var origin: ShoppingListItemOrigin
    var status: ShoppingListItemStatus

    var normalizedIngredientName: String {
        ingredientName.trimmingCharacters(in: .whitespacesAndNewlines).lowercased()
    }
}
