//
//  ShoppingListItemRecord.swift
//  Kitchen Companion
//
//  Created by Carmelo Stivala on 29/9/2026.
//

import Foundation
import SwiftData

// SwiftData model for one entry on the household's shopping list.
// originKind and originRecipeID together encode ShoppingListItemOrigin, since
// SwiftData cannot store an enum with an associated value directly.
// originKind is either "manual" or "autoGenerated".
@Model
final class ShoppingListItemRecord {
    @Attribute(.unique) var id: String
    var ingredientName: String
    var quantityAmount: Double
    var quantityUnit: String
    var originKind: String
    var originRecipeID: String?
    var statusRaw: String

    // Optional, nil until the item is bought and linked back to a pantry
    // ingredient by MarkShoppingItemPurchasedUseCase.
    var relatedIngredient: IngredientRecord?

    init(id: String, ingredientName: String, quantityAmount: Double, quantityUnit: String, originKind: String, originRecipeID: String?, statusRaw: String) {
        self.id = id
        self.ingredientName = ingredientName
        self.quantityAmount = quantityAmount
        self.quantityUnit = quantityUnit
        self.originKind = originKind
        self.originRecipeID = originRecipeID
        self.statusRaw = statusRaw
        self.relatedIngredient = nil
    }
}
