//
//  SwiftDataShoppingListRepository.swift
//  Kitchen Companion
//
//  Created by Carmelo Stivala on 29/9/2026.
//

import Foundation
import SwiftData

// SwiftData backed implementation of ShoppingListRepository.
// Converts between the persisted ShoppingListItemRecord and the plain
// ShoppingListItem the rest of the app already works with.
final class SwiftDataShoppingListRepository: ShoppingListRepository {
    private let context: ModelContext

    init(context: ModelContext) {
        self.context = context
    }

    func allItems() -> [ShoppingListItem] {
        let descriptor = FetchDescriptor<ShoppingListItemRecord>(sortBy: [SortDescriptor(\.ingredientName)])
        let records = (try? context.fetch(descriptor)) ?? []
        return records.map(Self.toDomain)
    }

    func item(withID id: String) -> ShoppingListItem? {
        let descriptor = FetchDescriptor<ShoppingListItemRecord>(predicate: #Predicate { $0.id == id })
        guard let record = try? context.fetch(descriptor).first else { return nil }
        return Self.toDomain(record)
    }

    func save(item: ShoppingListItem) {
        let targetID = item.id
        let descriptor = FetchDescriptor<ShoppingListItemRecord>(predicate: #Predicate { $0.id == targetID })
        let originKind: String
        let originRecipeID: String?
        switch item.origin {
        case .manuallyAdded:
            originKind = "manual"
            originRecipeID = nil
        case .autoGenerated(let recipeID):
            originKind = "autoGenerated"
            originRecipeID = recipeID.rawValue
        }
        let statusRaw = item.status == .pending ? "pending" : "purchased"

        if let existing = try? context.fetch(descriptor).first {
            existing.ingredientName = item.ingredientName
            existing.quantityAmount = item.quantityNeeded.amount
            existing.quantityUnit = item.quantityNeeded.unit.rawValue
            existing.originKind = originKind
            existing.originRecipeID = originRecipeID
            existing.statusRaw = statusRaw
        } else {
            let record = ShoppingListItemRecord(
                id: item.id,
                ingredientName: item.ingredientName,
                quantityAmount: item.quantityNeeded.amount,
                quantityUnit: item.quantityNeeded.unit.rawValue,
                originKind: originKind,
                originRecipeID: originRecipeID,
                statusRaw: statusRaw
            )
            context.insert(record)
        }
        try? context.save()
    }

    func delete(itemID: String) {
        let descriptor = FetchDescriptor<ShoppingListItemRecord>(predicate: #Predicate { $0.id == itemID })
        if let record = try? context.fetch(descriptor).first {
            context.delete(record)
            try? context.save()
        }
    }

    private static func toDomain(_ record: ShoppingListItemRecord) -> ShoppingListItem {
        let origin: ShoppingListItemOrigin
        if record.originKind == "autoGenerated", let recipeID = record.originRecipeID {
            origin = .autoGenerated(recipeID: RecipeIdentifier(rawValue: recipeID))
        } else {
            origin = .manuallyAdded
        }
        let status: ShoppingListItemStatus = record.statusRaw == "purchased" ? .purchased : .pending

        return ShoppingListItem(
            id: record.id,
            ingredientName: record.ingredientName,
            quantityNeeded: Quantity(amount: record.quantityAmount, unit: UnitOfMeasure(rawValue: record.quantityUnit) ?? .pieces),
            origin: origin,
            status: status
        )
    }
}
